export {default as Navbar } from './components/navbars/navbar'
export {default as Footer} from './components/footers/footer'
export {default as Layout} from './components/layouts/main'
export {default as Login} from './auth/Login'
export {default as Home} from './home/index'
export {default as Team} from './team/index'
export {default as Tournament} from './tournament/index'